Repository SWException/swe-docs, pull requests merged in 2021-01, with the labels that each got.

#42 Verifica Feature/piano di qualifica v. 0.0.10
  .gitignore
  Esterni/PianoDiQualifica/main.tex
  Esterni/PianoDiQualifica/res/configurazione.tex
  Esterni/PianoDiQualifica/res/frontespizio.tex
  Esterni/PianoDiQualifica/res/images/grafico_correttezza.png
  Esterni/PianoDiQualifica/res/images/grafico_gulpease.png
  Esterni/PianoDiQualifica/res/images/logo.jpg
  Esterni/PianoDiQualifica/res/images/vtestmodel.png
  Esterni/PianoDiQualifica/res/registro.tex
  Esterni/PianoDiQualifica/res/sections/introduzione.tex
  Esterni/PianoDiQualifica/res/sections/qualita_processo/qualita_processo.tex
  Esterni/PianoDiQualifica/res/sections/qualita_prodotto/qualita_prodotto.tex
  Esterni/PianoDiQualifica/res/sections/resoconto_verifica/resoconto_verifica.tex
  Esterni/PianoDiQualifica/res/sections/test/test.tex
  Esterni/PianoDiQualifica/res/sezioni.tex
  clean.sh
Labels: da modificare, da verificare

#30 Revisione feature/norme-di-progetto v.0.1.0
  .gitignore
  Interni/NormeDiProgetto/main.tex
  Interni/NormeDiProgetto/res/configurazione.tex
  Interni/NormeDiProgetto/res/frontespizio.tex
  Interni/NormeDiProgetto/res/images/ciclo_vita_ticket.jpg
  Interni/NormeDiProgetto/res/images/processo_validazione.png
  Interni/NormeDiProgetto/res/images/processo_verifica.png
  Interni/NormeDiProgetto/res/registro.tex
  Interni/NormeDiProgetto/res/sections/appendici.tex
  Interni/NormeDiProgetto/res/sections/introduzione.tex
  Interni/NormeDiProgetto/res/sections/processi_organizzativi/processi_organizzativi.tex
  Interni/NormeDiProgetto/res/sections/processi_primari/processi_primari.tex
  Interni/NormeDiProgetto/res/sections/processi_supporto/processi_supporto.tex
  Interni/NormeDiProgetto/res/sezioni.tex
  Interni/Verbali/VerbaleInterno2020-12-17/res/contenuto.tex
  Template/Documento/main.tex
  Template/Documento/res/configurazione.tex
  Template/Documento/res/frontespizio.tex
  Template/Documento/res/registro.tex
  clean.bat
  clean.sh
Labels: da approvare, da verificare

#46 Verifica feature/analisi dei requisiti
  .gitignore
  Esterni/AnalisiDeiRequisiti/main.tex
  Esterni/AnalisiDeiRequisiti/res/configurazione.tex
  Esterni/AnalisiDeiRequisiti/res/frontespizio.tex
  Esterni/AnalisiDeiRequisiti/res/images/UC/UC10.png
  Esterni/AnalisiDeiRequisiti/res/images/UC/UC12.png
  Esterni/AnalisiDeiRequisiti/res/images/UC/UC8.png
  Esterni/AnalisiDeiRequisiti/res/images/UC/attori.png
  Esterni/AnalisiDeiRequisiti/res/images/UC/cliente.png
  Esterni/AnalisiDeiRequisiti/res/images/UC/venditore.png
  Esterni/AnalisiDeiRequisiti/res/images/logo.jpg
  Esterni/AnalisiDeiRequisiti/res/registro.tex
  Esterni/AnalisiDeiRequisiti/res/sections/casi_uso/casi_uso_cliente.tex
  Esterni/AnalisiDeiRequisiti/res/sections/casi_uso/casi_uso_venditore.tex
  Esterni/AnalisiDeiRequisiti/res/sections/casi_uso/introduzione_casi_uso.tex
  Esterni/AnalisiDeiRequisiti/res/sections/descrizione_prodotto/descrizione_prodotto.tex
  Esterni/AnalisiDeiRequisiti/res/sections/introduzione.tex
  Esterni/AnalisiDeiRequisiti/res/sections/requisiti/requisiti.tex
  Esterni/AnalisiDeiRequisiti/res/sections/tracciamento/tracciamento.tex
  Esterni/AnalisiDeiRequisiti/res/sezioni.tex
  Interni/StudioDiFattibilita/res/sections/C1/C1.tex
  clean.sh
Labels: da verificare, documenti esterni

#44 Verifica feature/studio fattibilita
  .gitignore
  Interni/StudioDiFattibilita/main.tex
  Interni/StudioDiFattibilita/res/frontespizio.tex
  Interni/StudioDiFattibilita/res/images/logo.jpg
  Interni/StudioDiFattibilita/res/registro.tex
  Interni/StudioDiFattibilita/res/sections/C1/C1.tex
  Interni/StudioDiFattibilita/res/sections/C2/C2.tex
  Interni/StudioDiFattibilita/res/sections/C3/C3.tex
  Interni/StudioDiFattibilita/res/sections/C4/C4.tex
  Interni/StudioDiFattibilita/res/sections/C5/C5.tex
  Interni/StudioDiFattibilita/res/sections/C6/C6.tex
  Interni/StudioDiFattibilita/res/sections/C7/C7.tex
  Interni/StudioDiFattibilita/res/sections/introduzione.tex
Labels: da approvare, documenti interni

#43 Verifica feature/glossario v. 0.0.4
  .gitignore
  Esterni/Glossario/main.tex
  Esterni/Glossario/res/configurazione.tex
  Esterni/Glossario/res/frontespizio.tex
  Esterni/Glossario/res/images/logo.jpg
  Esterni/Glossario/res/registro.tex
  Esterni/Glossario/res/sections/glossario.tex
  Esterni/Glossario/res/sezioni.tex
  Interni/StudioDiFattibilita/res/sections/C7/C7.tex
  clean.bat
  clean.sh
Labels: da verificare
